apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-ca-issuer
  namespace: origin-ca-issuer
spec:
  selector:
    matchLabels:
      app: origin-ca-issuer
  replicas: 1
  template:
    metadata:
      labels:
        app: origin-ca-issuer
    spec:
      serviceAccountName: originissuer-control
      containers:
        - image: penumbra23/origin-ca-cluster-controller:latest
          name: origin-ca-cluster-controller
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      terminationGracePeriodSeconds: 10
