# [[file:../../README.org::*Adding an OriginClusterIssuer][Adding an OriginClusterIssuer:2]]
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginClusterIssuer
metadata:
  name: prod-issuer
  # This can now be any other namespace
  namespace: default
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: service-key
      key: key
      namespace: default
# Adding an OriginClusterIssuer:2 ends here
