apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: originclusterissuer-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: originclusterissuer-control
subjects:
  - kind: ServiceAccount
    name: originclusterissuer-control
    namespace: origin-ca-issuer
---
# bind the cert-manager internal approver to approve
# cert-manager.k8s.cloudflare.com CertificateRequests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-approve:cert-manager-k8s-cloudflare-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-approve:cert-manager-k8s-cloudflare-com
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
